name: Deploy

on:
  push:
    branches: [ master,feature/testimp/github-actions ]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: website
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: '16.16.0'
        cache: yarn
        cache-dependency-path: ./website/yarn.lock
    - name: git config
      run: |
        git config --global user.email "jj.y0sh1da@gmail.com"
        git config --global user.name "neon-izm"
    - run: yarn install --frozen-lockfile
    - run: yarn deploy
      env:
        GIT_USER: ${{ github.actor }}:${{ secrets.SOCIALGAME_GITHUB_TOKEN }}
