name: Deploy

on:
  push:
    branches: [ master,feature/testimp/github-actions ]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: website
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: '16.16.0'
        cache: yarn
        cache-dependency-path: ./website/yarn.lock
    - name: git config
      run: |
        git config --global user.email "docusaurus@example.com"
        git config --global user.name "docusaurus"
    - name: Deploy to Github Pages
      env:
        GIT_USER: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn install --frozen-lockfile
        yarn deploy
