name: Deploy

on:
  push:
    branches: [ master,feature/testimp/github-actions ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: git config
      run: |
        git config --global user.email "jj.y0sh1da@gmail.com"
        git config --global user.name "neon-izm"
    - run: yarn install
    - run: yarn deploy
      env:
        GIT_USER: ${{ github.actor }}:${{ secrets.SOCIALGAME_GITHUB_TOKEN }}
